config/routes.rb
RunAllTest::Application.routes.draw do
  resources :identifications
  root :to => 'identifications#new'
  match '/home', to: 'identifications#new'
  match '/select', to:'identifications#select'
  
end

app/models/identification.rb
class Identification < ActiveRecord::Base
  attr_accessible :password, :token, :userName, :selectClass
end

app/models/login.rb
require 'singleton'

#This class is use to log to salesforce in order to use webservices
class Login
  include Singleton
   
  attr_reader :sessionId
    
  def getSessionId username, password, token
    client = Savon.client(wsdl: "app/assets/wsdl/enterprise.wsdl")
   #response = client.request :urn, :login, body: {username: username, password: password+token}
    message = { username: username, password: password+token }
    response = client.call(:login, message: message)
    data = response.to_hash
    return data[:login_response][:result]
    
  end
  
end


app/models/report.rb
class Report

	def initialize(organizationName)
		@organizationName = organizationName
		@testClasses = Array.new
	end

  	def testClasses
  		@testClasses
  	end

	def testClasses=(testClasses)
	  	@testClasses = testClasses
	end

	def organizationName
  		@organizationName
  	end

	def organizationName=(organizationName)
	  	@organizationName = organizationName
	end

end

app/models/salesforcewebservices.rb
class Salesforcewebservices
    
  
  def self.getResults username, password, token
    result = Login.instance.getSessionId(username, password, token)
    wsdlURL = createWsdlUrl result[:server_url]
    headers = {'apex:SessionHeader' =>{'apex:sessionId' => result[:session_id]}, 'apex:DebuggingHeader' =>{'apex:debugLevel' => 'Callout', 'apex:categories' => {'apex:category'=>'Callout', 'apex:level'=>'INFO'}}}
    client = Savon.client(
          wsdl: 'app/assets/wsdl/apex.wsdl',
          endpoint: wsdlURL,
          namespace: 'http://soap.sforce.com/2006/08/apex',
          namespace_identifier: :apex,
          soap_header: headers,
          read_timeout: 6000
    )
    response = client.call(:run_tests) do
                message run_tests_request:{ all_tests: :true}
                
              end
    data = response.to_hash   
  end
  
def self.createWsdlUrl serverUrl
    urlArray = Array.new
    urlArray = serverUrl.split('/')
    wsdlUrl = urlArray[0]+'//'+urlArray[2]+'/'+urlArray[3]+'/'+urlArray[4]+'/s/'+urlArray[6]
end
def self.getAllTestClasses username, password, token
    result = Login.instance.getSessionId(username, password, token)
    wsdlURL = result[:server_url]
    puts wsdlURL
    headers = {'urn:SessionHeader' =>{'urn:sessionId' => result[:session_id]}}
    client = Savon.client(
          wsdl: 'app/assets/wsdl/enterprise.wsdl',
          endpoint: wsdlURL,
          namespace: 'urn:enterprise.soap.sforce.com',
          namespace_identifier: :urn,
          soap_header: headers,
          read_timeout: 6000
    )
    message = { query_string: 'select name, body from ApexClass order by name'}
    response = client.call(:query, message: message)
    data = response.to_hash 
end  

  
end

app/models/test_class_item.rb
class TestClassItem 


  def initialize(className, isSelected)
  	@className = className
    @isSelected = isSelected
  end	

  def className=(className)
  	@className = className
  end

  def className
  	@className
  end

  def isSelected
  	@isSelected
  end

  def isSelected=(isSelected)
  	@isSelected = isSelected
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  require 'test_class_item'
  require 'report'
   
  def new
    @identification = Identification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @identification }
    end
  end

   def create
    @successes = Hash.new
    @failures = Hash.new
    @numberTests = Hash.new
    @overAllCodeCoverage = Hash.new
    @numberFailures = Hash.new
    @totalTime = 0
    @codeCoverage = Hash.new
    choice = params[:identification][:selectClass]
    if choice == '1'
      @testClasses = selectTestClasses params
      render 'listClasses'
    else
      @identification = Identification.new(params[:identification])
      result = Salesforcewebservices.getResults params[:identification][:userName], params[:identification][:password], params[:identification][:token]
      @successes =  result[:run_tests_response][:result][:successes] if !result[:run_tests_response][:result][:successes].nil?
           
      @failures = result[:run_tests_response][:result][:failures] if !result[:run_tests_response][:result][:failures].nil?
      
      
      @numberTests = result[:run_tests_response][:result][:num_tests_run] if !result[:run_tests_response][:result][:num_tests_run].nil?
            
      if !result[:run_tests_response][:result][:code_coverage].nil?
        @overAllCodeCoverage = processOverAllCodeCoverage result[:run_tests_response][:result][:code_coverage]
      end
      
      @numberFailures = result[:run_tests_response][:result][:num_failures] if !result[:run_tests_response][:result][:num_failures].nil?
      @totalTime = (result[:run_tests_response][:result][:total_time].to_i/(1000*60))%60 if !result[:run_tests_response][:result][:total_time].nil?
      render 'show'
      
    end  
  end


  def processOverAllCodeCoverage codeCoverages
    puts codeCoverages
    overAllAmount = 0;
    overAllLines = 0;
    @codeCoverage = Hash.new
    coverage = 0;
    counter = 0;
    codeCoverages.each do |code|
      if code[:num_locations_not_covered].to_i > 0
        coverage =  ((code[:num_locations].to_i - code[:num_locations_not_covered].to_i)*100)/code[:num_locations].to_i
        overAllAmount += coverage
      else
        coverage = 100
        overAllAmount += 100
      end 
      overAllLines += code[:num_locations].to_i
      @codeCoverage[code[:name]] = coverage
      counter += 1
    end
    overAllAmount / counter
  end  

  def selectTestClasses params
   
    result = Salesforcewebservices.getAllTestClasses params[:identification][:userName], params[:identification][:password], params[:identification][:token]
    testClasses = Array.new 
    testClassesHash =  result[:query_response][:result][:records]
    report = Report.new('my org')
    testClassesHash.each do |testClass|
      if isTestClass testClass
        report.testClasses.push TestClassItem.new(testClass[:name].to_s, false)
        testClasses.push TestClassItem.new(testClass[:name].to_s, false)
      end
    end  
    testClasses
  end


  def isTestClass testClass
    body = testClass[:body].to_s
    name = testClass[:name].to_s
    if (body.include? "@isTest") || (body.include? "testMethod") || (name.include? "Test") || (name.include? "test") 
      true
    end
  end  
 
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/identifications_helper.rb
module IdentificationsHelper
end

app/views/identifications/_form.html.erb

  <%= form_for @identification, :html => {:class => "form-horizontal"} do |f| %>
    <% if @identification.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@identification.errors.count, "error") %> prohibited this identification from being saved:
        </h2>

        <ul>
        <% @identification.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
     <div class="control-group" >
      <label class="control-label" for="inputEmail"><b >UserName</b></label>
      <div class="controls">
        <%= f.text_field :userName %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputPassword"><b>Password</b></label>
      <div class="controls">
        <%= f.password_field :password %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputPassword"><b>Token</b></label>
      <div class="controls">
        <%= f.password_field :token %>
      </div>
    </div>
     <div class="control-group">
      <label class="control-label" for="inputPassword"><b>Select Classes</b></label>
      <div class="controls">
       <%= f.check_box :selectClass %> 
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <button id="submitident" type="submit" class="btn btn-primary" data-loading-text="Loading...">Start The Race</button>
      </div>
    </div>
    

  <% end %>

app/views/identifications/edit.html.erb
<h1>Editing identification</h1>

<%= render 'form' %>

<%= link_to 'Show', @identification %> |
<%= link_to 'Back', identifications_path %>

app/views/identifications/index.html.erb
<h1>Listing identifications</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @identifications.each do |identification| %>
  <tr>
    <td><%= identification.userName %></td>
    <td><%= identification.password %></td>
    <td><%= identification.token %></td>
    <td><%= link_to 'Show', identification %></td>
    <td><%= link_to 'Edit', edit_identification_path(identification) %></td>
    <td><%= link_to 'Destroy', identification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Identification', new_identification_path %>

app/views/identifications/listClasses.html.erb
<div class=" row">
	<div class="span9 offset1">
		<h5>Test Classes</h5>
		<br/>
		<div class="control-group">
		      <div class="controls">
		        <button id="runclasstop" type="button" class="btn btn-primary" >Start The Race</button>
		      </div>
		</div>
		<table id="tableau" class="table table-striped table-bordered">
		  <tr>
		    <th><input id="selectall" type="checkbox" /></th>
		    <th>Class Name</th>  
		  </tr>

		<% @testClasses.each do |testClass| %>
		  <tr>
		    <td><input class="select" type="checkbox" value="<% testClass.isSelected %>"/></td>
		    <td><%= testClass.className %></td>
		   </tr>
		<% end %>

		</table>
		<div class="control-group">
		      <div class="controls">
		        <button id="runclassbottom" type="button" class="btn btn-primary" >Start The Race</button>
		      </div>
		</div>
	</div>
</div>

app/views/identifications/new.html.erb
<div class="row" style="float:right;">
  <div id="form" class="span9 offset4">
	<%= render 'form' %>
	
  </div>
  <div id="loader" class="span9 offset7" style="display:none;">
	<img src="/assets/ajax_loader_gray_512.gif" >
  </div>
</div>

app/views/identifications/show.html.erb
<div class="row">
	<div class="span9 offset1">
		<h5>Run All Tests Result For : <%= @identification[:userName]%></h5>
		<p id="notice"><%= notice %></p>
		<br/>
		<a href="/home" class="btn btn-primary">Home</a>
		<br/>
		<table class="table table-bordered">
		  <tr>
		    <th>Number Of Test</th>
		    <th>Number Of Failures</th>
		    <th>Overall Code Coverage</th>
		    <th>Total Ellapsed Time</th>
		  </tr>


		  <tr>
		    <td><%= @numberTests %></td>
		    <td><%= @numberFailures %></td>
		    <td><%= @overAllCodeCoverage%> </td>
		    <td><%= @totalTime %> min </td>
		  </tr>

		</table>

		<br/>
		
		<h5>Classes with failures</h5>
		<br/>
		<table class="table table-striped table-bordered">
		  <tr>
		    <th>Class Name</th>
		    <th>Method Name</th>
		    <th>Message</th>
		    <th>Stack Trace</th>
		  </tr>

		<% @failures.each do |failure| %>
		  <tr>
		    <td><%= failure[:name] %></td>
		    <td><%= failure[:method_name] %></td>
		 	<td><%= failure[:message] %></td>
		    <td><%= failure[:stack_trace] %></td>
		  </tr>
		<% end %>
		</table>
		
		
	  <h5>Code Coverage By Class</h5>
	  <br/>
		    <table id="codecoverage" class="table table-bordered">
			  <tr>
			    <th>Class Name</th>
			    <th>Code Coverage</th>  
			  </tr>
		    <% @codeCoverage.each do |className, coverage| %> 
			  	<tr>
				    <td><%= className %></td>
				    <td class="coverage"><%= coverage %></td>
				</tr>
		    <% end %>
		    </table>

		
		<a href="/home" class="btn btn-primary">Home</a>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer>


</footer>

app/views/layouts/_header.html.erb
<header>
	<img class="span5 offset3"src="/assets/ratrace.jpg"></img>	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RunAllTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= render 'layouts/header'%>
	
		<%= yield %>
	
	<%= render 'layouts/footer'%>
</div>
</body>
</html>